# Generated by Django 5.2.2 on 2025-11-24 17:30

from django.db import migrations

from django.contrib.auth.hashers import make_password
from dotenv import load_dotenv
import os

load_dotenv()

def create_superuser(apps, scheme_editor):
    User = apps.get_model("accounts", "CustomUser")

    if not User.objects.filter(email=os.getenv('email')).exists():

        User.objects.create(
            username=os.getenv('username'),
            email=os.getenv('email'),
            password=make_password(os.getenv('password')),
            is_superuser=True,
            is_staff=True,
            is_active=True,
        )

class Migration(migrations.Migration):

    dependencies = [
            ('accounts', '0002_alter_customuser_managers_alter_customuser_email_and_more'),
    ]


    operations = [
        migrations.RunPython(create_superuser)
    ]
