# Generated by Django 5.2.2 on 2025-06-16 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_blogpostcategory_alter_blogpostvote_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='community.blogpostcategory'),
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostcategory',
            name='category',
            field=models.CharField(choices=[('TOP', 'top'), ('HOT', 'hot'), ('NEW', 'new'), ('RISING', 'rising'), ('CONTROVERSIAL', 'controversial'), ('GILDED', 'gilded'), ('PROMOTED', 'promoted')], max_length=50),
        ),
    ]
