# Generated by Django 5.2 on 2025-07-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_blogpost_category_blogpostvote_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostvote',
            name='downvote_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='upvote_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='community',
        ),
        migrations.AlterField(
            model_name='blogpostvote',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_vote', to='community.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='community',
            field=models.ManyToManyField(related_name='community_posts', to='community.community'),
        ),
    ]
