# Generated by Django 5.2 on 2025-08-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_blogpostvote_downvote_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpostvote',
            unique_together={('post', 'upvote_count', 'downvote_count')},
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='user',
        ),
    ]
