# Generated by Django 5.2 on 2025-09-01 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_blogpostvote_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogpostvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='downvote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvote_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='upvote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
