# Generated by Django 5.2 on 2025-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_blogpostvote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostvote',
            name='downvote_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='upvote_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
