# Generated by Django 5.2 on 2025-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_blogpostvote_downvote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostvote',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpostvote',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
