# Generated by Django 5.2 on 2025-09-01 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_blogpostvote_downvote_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostvote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='downvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='downvote_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpostvote',
            name='upvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvote_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
