# Generated by Django 5.2 on 2025-09-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_remove_blogpostvote_downvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostvote',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='blogpostvote',
            name='upvote_count',
        ),
    ]
